# Generated by Django 3.1.7 on 2023-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_highest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
