# Generated by Django 3.1.7 on 2023-10-17 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_current_highest_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid_count', models.PositiveIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
