# Generated by Django 3.1.7 on 2023-10-18 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20231018_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_timestamp',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
